using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.Collections;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Data.Entity;

namespace EtsyRobot.Storage
{
    // This class enables two-way data binding as well as sorting.The class derives from ObservableCollection<T> and
    // adds an explicit implementation of IListSource.The GetList() method of IListSource is implemented to return an 
    // IBindingList implementation that stays in sync with the ObservableCollection.The IBindingList implementation generated by 
    // ToBindingList supports sorting.The ToBindingList extention method is defined in the EntityFramework assembly.
    public class ObservableListSource<T> : ObservableCollection<T>, IListSource
            where T : class
    {
        private IBindingList _bindingList;

        bool IListSource.ContainsListCollection { get { return false; } }

        IList IListSource.GetList()
        {
            return _bindingList ?? (_bindingList = this.ToBindingList());
        }
    }
}
